file_ext: ".md" #dont forget initial dot 
editor: "" #empty for default system environment variable $EDITOR

notes_folder: ".tasknotes"  #relative to user home folder
# notes_folder: "Documents/golang/tasknotes/"

open_tasknote_after_creation: 1
